IO-5 - Create a java spring template for backend of the application and establish structure for the project
veramenti/io-backend pull request #1
Opened 2023-04-06 22:32 UTC by Ch-Adrian

2023-04-07 15:10 UTC, Ch-Adrian commented on BackendIO/src/main/java/pl/edu/agh/cs/io/backendio/controller/ExampleController.java
Jeżeli chodzi o routes to zwłaszcza po Twoim tłumaczeniu rozumiem jak to mniej więcej działa, ale w springu widzę, że jest jakieś inne nazewnictwo trochę i RestControllery (i ogólnie controllery springa) odpowiadają za routy (takie jak są w expressie na przykład). Z services o którym mówisz, które wykonują jakieś jedno polecenie na bazie to w springu z tego co wiem odpowiada właśnie repository. Pozostawiłbym na razie nazewnictwo zgodne z nazwami adnotacji springa. Jeżeli przyda się nowy poziom abstrakcji to myślę, że na bieżąco można go dodać.

2023-04-07 15:29 UTC, Ch-Adrian commented on BackendIO/src/main/java/pl/edu/agh/cs/io/backendio/controller/ExampleController.java
> +    public ResponseEntity<Example> getExampleById(@PathVariable("id") int exampleId){
getExampleById to jest konwencja ze springa z komponentu repository. Myślę, że w komponencie controller można zmienić tak jak mówisz.

2023-04-07 15:50 UTC, Ch-Adrian commented on BackendIO/src/main/java/pl/edu/agh/cs/io/backendio/controller/ExampleController.java
> +@RequestMapping("/api/examples")
ok, zostawię `/examples`

2023-04-07 15:51 UTC, Ch-Adrian commented on BackendIO/src/main/java/pl/edu/agh/cs/io/backendio/controller/ExampleController.java
> +    @PostMapping()
już zmienione

2023-04-07 15:53 UTC, Ch-Adrian commented on BackendIO/src/main/java/pl/edu/agh/cs/io/backendio/controller/ExampleController.java
> +    @PostMapping()
zostawię `id` i poczekam też na bazę

2023-04-07 16:09 UTC, Ch-Adrian commented on BackendIO/src/main/java/pl/edu/agh/cs/io/backendio/controller/ExampleController.java
> +    public List<Example> getAllExamples(){
ok

2023-04-07 16:09 UTC, Ch-Adrian commented on BackendIO/src/main/java/pl/edu/agh/cs/io/backendio/controller/ExampleController.java
> +    public ResponseEntity<Example> saveExample(@RequestBody Example example){
ok

2023-04-07 16:16 UTC, Ch-Adrian commented on BackendIO/src/main/java/pl/edu/agh/cs/io/backendio/controller/ExampleController.java
> +    public ResponseEntity<Example> updateExample(@PathVariable("id") int exampleId, @RequestBody Example example){
Jak patrzyłem na różne kody, zwłaszcza na stronach, gdzie uczą praktyk programowania ([](https://www.javaguides.net/2021/10/spring-boot-crud-rest-api-project-using-IntelliJ-IDEA.html)) to argument RequestBody nazywają tak jak nazywa się obiekt tego argumentu.

2023-04-07 16:31 UTC, Ch-Adrian commented on BackendIO/src/main/java/pl/edu/agh/cs/io/backendio/model/Example.java
> +package pl.edu.agh.cs.io.backendio.model;
jak dodamy bazę danych wtedy doda się odpowiednie dependencies do gradla i można dodawać komponenty ORM lub ODM

2023-04-07 16:32 UTC, Ch-Adrian commented on BackendIO/src/main/java/pl/edu/agh/cs/io/backendio/service/ExampleService.java
> +        if(this.arrayList.size() <= id || id < 0) throw new ExampleNotFoundException("Example of id: "+String.valueOf(id)+" is not found.");
racja, chyba nawet łatwiej się tak pisze wstawianie wartości do stringa

2023-04-12 14:26 UTC, veramenti commented on BackendIO/src/main/java/pl/edu/agh/cs/io/backendio/controller/ExampleController.java
> +    public ResponseEntity<Example> updateExample(@PathVariable("id") int exampleId, @RequestBody Example example){
Ja bym dał po prostu `body` zamiast `exampleDetails`, ale może zostać jak chcesz

W konkretnym przypadku jest okej ale jakby body nie dotyczyło bezpośrednio example to jakbyś je nazwał?

2023-04-12 14:44 UTC, Ch-Adrian commented on BackendIO/src/main/java/pl/edu/agh/cs/io/backendio/controller/ExampleController.java
> +    public ResponseEntity<Example> updateExample(@PathVariable("id") int exampleId, @RequestBody Example example){
Pewnie tak jak mówisz `body` tak byłoby najprościej albo pożyczyłbym nazwę z adnotacji `requestBody`. Na razie niech będzie jak jest, jak będziemy dodawać kolejne controllery springowe to też można będzie zmienić.

2023-04-15 02:28 UTC, veramenti requested changes
Ostatni commit powoduje że przy próbie uruchomienia rzuca błędami - odpalałeś przed push'em?
![obraz](https://user-images.githubusercontent.com/105918802/232178796-607ab190-c16f-464c-aaef-376eab279bf0.png)

2023-04-15 07:37 UTC, Ch-Adrian commented
o faktycznie, sorka , Musiałem nie sprawdzić tego po zmianie na uri. Tam nie powinno być cudzysłowów, zaraz poprawię.

2023-04-15 08:12 UTC, veramenti commented
Miedzy innymi w profesjonalnych projektach po to pisze się testy :P

2023-04-15 08:14 UTC, veramenti commented
Nie podoba mi się to że jest katalog repozytorium io-backend i dopiero w nim znajduje się właściwy projekt BackendIO - dlaczego?

2023-04-15 08:26 UTC, Ch-Adrian commented
ok, zmienię katalog projektu na ten główny io-backend. Właśnie tu mam też pytanie. Dlaczego mamy taki podział, że są dwa repozytoria jedno na backend, a drugie na frontend? A nie mamy tego na jednym repo dwa katalogi backend i frontend obok siebie?

2023-04-15 08:45 UTC, veramenti commented
Ponieważ są to dwa osobne projekty
Pierwszy to po prostu api, drugi to narzędzie to łatwej obsługi tego api

Ponadto oba projekty są napisane w innych technologiach, a co za tym idzie - obsługują je inne IDE

Kolejnym chyba najważniejszym powodem jest to, że wtedy projekty są od siebie odseparowane co ułatwia zarówno zarządzanie nimi, jak i ich rozwijanie
Ogólnie raczej zawsze kiedy da się coś odseparować, powinniśmy to robić

Noi przy deploy'u łatwiej jest się z tym ogarniać (a na pewno wygodniej)

2023-04-15 09:19 UTC, veramenti approved these changes

2023-04-15 09:20 UTC, merged